name: rishuden
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  intl: ^0.19.0
  cupertino_icons: ^1.0.6 # これは既にあるかもしれません
  flutter_rating_bar: ^4.0.0 # ★これを追加してください★
  provider: ^6.0.0
  http: ^1.4.0
  icalendar_parser: ^2.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background_plaza.png
    - assets/icon_takoyaki.png
    - assets/button_unit_review.png
    - assets/button_ranking.png
    - assets/button_dressup.png
    - assets/button_timetable.png
    - assets/button_park_icon.png
    - assets/button_unit_review_active.png
    - assets/button_ranking_active.png
    - assets/button_dressup_active.png
    - assets/button_timetable_active.png
    - assets/button_park_icon_active.png
    - assets/character_swordman.png
    - assets/character_wizard.png
    - assets/character_gorilla.png
    - assets/character_merchant.png
    - assets/character_adventurer.png
    - assets/character_god.png
    - assets/character_takuji.png
    - assets/question_background_image.png
    - assets/countdown.png
    - assets/ranking_guild_background.png
    - assets/ui_takoyaki_bar.png
    - assets/icon_plus.png
    - assets/ui_level_hp_bg.png
    - assets/banner_news.png
    - assets/title.png
    - assets/oztech.png
    - assets/potipoti.png
    - assets/bottom_bar_bg.png
    - assets/stage.png
    - assets/make_quest.png
    - assets/takoyaki.png
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: fonts/NotoSansJP-Regular.ttf
    - family: misaki
      fonts:
        - asset: fonts/misaki_gothic.ttf
    - family: display_free_tfb
      fonts:
        - asset: fonts/DISPLAY FREE TFB.ttf
    - family: DISPLAY FREE TFB
      fonts:
        - asset: fonts/DISPLAY FREE TFB.ttf
