name: rishuden
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background_plaza.png
    - assets/icon_takoyaki.png
    - assets/button_unit_review.png
    - assets/button_ranking.png
    - assets/button_dressup.png
    - assets/button_timetable.png
    - assets/character_swordman.png
    - assets/character_wizard.png
    - assets/character_gorilla.png
    - assets/character_marchant.png
    - assets/character_adventurer.png
    - assets/character_god.png
    - assets/character_takuji.png

    - assets/ranking_guild_background.png

  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: fonts/NotoSansJP-Regular.ttf
