name: rishuden
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  cloud_firestore:
  firebase_auth:
  intl:
  cupertino_icons: # これは既にあるかもしれません
  flutter_rating_bar: # ★これを追加してください★
  provider:
  http:
  icalendar_parser:
  url_launcher:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background_plaza.png
    - assets/icon_takoyaki.png
    - assets/buttons/common_navigation/credit_active.png
    - assets/buttons/common_navigation/credit_inactive.png
    - assets/buttons/common_navigation/dress_active.png
    - assets/buttons/common_navigation/dress_inactive.png
    - assets/buttons/common_navigation/park_active.png
    - assets/buttons/common_navigation/park_inactive.png
    - assets/buttons/common_navigation/ranking_active.png
    - assets/buttons/common_navigation/ranking_inactive.png
    - assets/buttons/common_navigation/timetable_active.png
    - assets/buttons/common_navigation/timetable_inactive.png
    - assets/character_swordman.png
    - assets/character_wizard.png
    - assets/character_gorilla.png
    - assets/character_merchant.png
    - assets/character_adventurer.png
    - assets/character_god.png
    - assets/character_takuji.png
    - assets/question_background_image.png
    - assets/countdown.png
    - assets/ranking_guild_background.png
    - assets/ui_takoyaki_bar.png
    - assets/icon_plus.png
    - assets/ui_level_hp_bg.png
    - assets/banner_news.png
    - assets/title.png
    - assets/oztech.png
    - assets/potipoti.png
    - assets/bottom_bar_bg.png
    - assets/stage.png
    - assets/make_quest.png
    - assets/takoyaki.png
    - assets/crack_overlay.png
    - assets/takoyaki_off.png
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: fonts/NotoSansJP-Regular.ttf
    - family: misaki
      fonts:
        - asset: fonts/misaki_gothic.ttf
    - family: display_free_tfb
      fonts:
        - asset: fonts/DISPLAY FREE TFB.ttf
    - family: DISPLAY FREE TFB
      fonts:
        - asset: fonts/DISPLAY FREE TFB.ttf
